services:
  backend:
    build: ./backend
    ports:
      - "8085:8085"
    restart: always
    env_file:
      - ./backend/.env

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
